// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MsmtApp.Models.EntityFramework.DBContext;
using NetTopologySuite.Geometries;

#nullable disable

namespace MsmtApp.Migrations
{
    [DbContext(typeof(MsmtDBContext))]
    [Migration("20231107100200_migrationsMsmt")]
    partial class migrationsMsmt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MsmtApp.Models.Class_County", b =>
                {
                    b.Property<int>("CountyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountyId"), 1L, 1);

                    b.Property<string>("CountyAdminLevel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CountyAreaId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Geometry>("CountyCoordinates")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<string>("CountyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("CountyId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("DB_County");
                });

            modelBuilder.Entity("MsmtApp.Models.Class_FourDigitActivityGroup", b =>
                {
                    b.Property<int>("FDAG_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FDAG_id"), 1L, 1);

                    b.Property<string>("FDAG_Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FDAG_Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FDAG_FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FDAG_RGB_B")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FDAG_RGB_G")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FDAG_RGB_R")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FDAG_Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IndustryGroupId")
                        .HasColumnType("int");

                    b.HasKey("FDAG_id");

                    b.HasIndex("IndustryGroupId");

                    b.ToTable("DB_FourDigitActivityGroup");
                });

            modelBuilder.Entity("MsmtApp.Models.Class_IndustrialUnit", b =>
                {
                    b.Property<int>("IndustryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndustryId"), 1L, 1);

                    b.Property<string>("CentralOffice")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FDAG_id")
                        .HasColumnType("int");

                    b.Property<string>("FixMe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ManagingName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SourceData")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IndustryId");

                    b.HasIndex("FDAG_id");

                    b.ToTable("DB_IndustrialUnit");
                });

            modelBuilder.Entity("MsmtApp.Models.Class_IndustryGroup", b =>
                {
                    b.Property<int>("IndustryGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndustryGroupId"), 1L, 1);

                    b.Property<string>("IndustryGroupCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IndustryGroupColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IndustryGroupFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IndustryGroupTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IndustryRGB_B")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IndustryRGB_G")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IndustryRGB_R")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IndustryGroupId");

                    b.ToTable("DB_IndustryGroup");

                    b.HasData(
                        new
                        {
                            IndustryGroupId = 33,
                            IndustryGroupCode = "33",
                            IndustryGroupColor = "#de2727",
                            IndustryGroupFullName = "ابزارپزشكي-اپتيكي-دقيق-ساعت(33)",
                            IndustryGroupTitle = "ابزارپزشكي-اپتيكي-دقيق-ساعت",
                            IndustryRGB_B = "39",
                            IndustryRGB_G = "39",
                            IndustryRGB_R = "222"
                        },
                        new
                        {
                            IndustryGroupId = 10,
                            IndustryGroupCode = "10",
                            IndustryGroupColor = "#7e4f07",
                            IndustryGroupFullName = "استخراج زغال سنگ ولينيت ..(10)",
                            IndustryGroupTitle = "استخراج زغال سنگ ولينيت",
                            IndustryRGB_B = "7",
                            IndustryRGB_G = "79",
                            IndustryRGB_R = "126"
                        },
                        new
                        {
                            IndustryGroupId = 14,
                            IndustryGroupCode = "14",
                            IndustryGroupColor = "#d18d25",
                            IndustryGroupFullName = "استخراج سايرمعادن(14)",
                            IndustryGroupTitle = "استخراج سايرمعادن",
                            IndustryRGB_B = "37",
                            IndustryRGB_G = "141",
                            IndustryRGB_R = "209"
                        },
                        new
                        {
                            IndustryGroupId = 22,
                            IndustryGroupCode = "22",
                            IndustryGroupColor = "#7fcf1a",
                            IndustryGroupFullName = "انتشاروچاپ وتكثير(22)",
                            IndustryGroupTitle = "انتشاروچاپ وتكثير",
                            IndustryRGB_B = "26",
                            IndustryRGB_G = "207",
                            IndustryRGB_R = "127"
                        },
                        new
                        {
                            IndustryGroupId = 37,
                            IndustryGroupCode = "37",
                            IndustryGroupColor = "#cecf1a",
                            IndustryGroupFullName = "بازيافت(37)",
                            IndustryGroupTitle = "بازيافت",
                            IndustryRGB_B = "26",
                            IndustryRGB_G = "207",
                            IndustryRGB_R = "206"
                        },
                        new
                        {
                            IndustryGroupId = 18,
                            IndustryGroupCode = "18",
                            IndustryGroupColor = "#1acf96",
                            IndustryGroupFullName = "پوشاك وعمل آوردن پوست خز(18)",
                            IndustryGroupTitle = "پوشاك وعمل آوردن پوست خز",
                            IndustryRGB_B = "150",
                            IndustryRGB_G = "207",
                            IndustryRGB_R = "26"
                        },
                        new
                        {
                            IndustryGroupId = 20,
                            IndustryGroupCode = "20",
                            IndustryGroupColor = "#1ab9cf",
                            IndustryGroupFullName = "چوب ومحصولات چوبي بجزمبل(20)",
                            IndustryGroupTitle = "چوب ومحصولات چوبي بجزمبل",
                            IndustryRGB_B = "207",
                            IndustryRGB_G = "185",
                            IndustryRGB_R = "26"
                        },
                        new
                        {
                            IndustryGroupId = 19,
                            IndustryGroupCode = "19",
                            IndustryGroupColor = "#781acf",
                            IndustryGroupFullName = "دباغي -چرم -كيف-چمدان-كفش(19)",
                            IndustryGroupTitle = "دباغي -چرم -كيف-چمدان-كفش",
                            IndustryRGB_B = "207",
                            IndustryRGB_G = "26",
                            IndustryRGB_R = "120"
                        },
                        new
                        {
                            IndustryGroupId = 32,
                            IndustryGroupCode = "32",
                            IndustryGroupColor = "#cf1abc",
                            IndustryGroupFullName = "راديوتلويزيون وسايل ارتباط(32)",
                            IndustryGroupTitle = "راديوتلويزيون وسايل ارتباط",
                            IndustryRGB_B = "188",
                            IndustryRGB_G = "26",
                            IndustryRGB_R = "207"
                        },
                        new
                        {
                            IndustryGroupId = 27,
                            IndustryGroupCode = "27",
                            IndustryGroupColor = "#1e34af",
                            IndustryGroupFullName = "ساخت فلزات اساسي(27)",
                            IndustryGroupTitle = "ساخت فلزات اساسي",
                            IndustryRGB_B = "175",
                            IndustryRGB_G = "52",
                            IndustryRGB_R = "30"
                        },
                        new
                        {
                            IndustryGroupId = 21,
                            IndustryGroupCode = "21",
                            IndustryGroupColor = "#1eaf67",
                            IndustryGroupFullName = "ساخت كاغذومحصولات كاغذي(21)",
                            IndustryGroupTitle = "ساخت كاغذومحصولات كاغذي",
                            IndustryRGB_B = "130",
                            IndustryRGB_G = "175",
                            IndustryRGB_R = "30"
                        },
                        new
                        {
                            IndustryGroupId = 29,
                            IndustryGroupCode = "29",
                            IndustryGroupColor = "#2f83ff",
                            IndustryGroupFullName = "ساخت ماشين آلات وتجهيزات(29)",
                            IndustryGroupTitle = "ساخت ماشين آلات وتجهيزات",
                            IndustryRGB_B = "255",
                            IndustryRGB_G = "131",
                            IndustryRGB_R = "47"
                        },
                        new
                        {
                            IndustryGroupId = 17,
                            IndustryGroupCode = "17",
                            IndustryGroupColor = "#942fff",
                            IndustryGroupFullName = "ساخت منسوجات(17)",
                            IndustryGroupTitle = "ساخت منسوجات",
                            IndustryRGB_B = "255",
                            IndustryRGB_G = "47",
                            IndustryRGB_R = "148"
                        },
                        new
                        {
                            IndustryGroupId = 24,
                            IndustryGroupCode = "24",
                            IndustryGroupColor = "#9d6c33",
                            IndustryGroupFullName = "ساخت موادومحصولات شيميائي(24)",
                            IndustryGroupTitle = "ساخت موادومحصولات شيميائي",
                            IndustryRGB_B = "51",
                            IndustryRGB_G = "108",
                            IndustryRGB_R = "157"
                        },
                        new
                        {
                            IndustryGroupId = 45,
                            IndustryGroupCode = "45",
                            IndustryGroupColor = "#0a5687",
                            IndustryGroupFullName = "ساختمان(45)",
                            IndustryGroupTitle = "ساختمان",
                            IndustryRGB_B = "135",
                            IndustryRGB_G = "86",
                            IndustryRGB_R = "10"
                        },
                        new
                        {
                            IndustryGroupId = 35,
                            IndustryGroupCode = "35",
                            IndustryGroupColor = "#0c4645",
                            IndustryGroupFullName = "سايرتجهيزات حمل ونقل(35)",
                            IndustryGroupTitle = "تجهيزات حمل ونقل",
                            IndustryRGB_B = "69",
                            IndustryRGB_G = "70",
                            IndustryRGB_R = "12"
                        },
                        new
                        {
                            IndustryGroupId = 74,
                            IndustryGroupCode = "74",
                            IndustryGroupColor = "#1acf96",
                            IndustryGroupFullName = "سايرفعاليتهاي خدمات مهندسي(74)",
                            IndustryGroupTitle = "فعاليتهاي خدمات مهندسي",
                            IndustryRGB_B = "150",
                            IndustryRGB_G = "207",
                            IndustryRGB_R = "26"
                        },
                        new
                        {
                            IndustryGroupId = 26,
                            IndustryGroupCode = "26",
                            IndustryGroupColor = "#1ab9cf",
                            IndustryGroupFullName = "سايرمحصولات كاني غيرفلزي(26)",
                            IndustryGroupTitle = "ساير محصولات كاني غيرفلزي",
                            IndustryRGB_B = "207",
                            IndustryRGB_G = "185",
                            IndustryRGB_R = "26"
                        },
                        new
                        {
                            IndustryGroupId = 63,
                            IndustryGroupCode = "63",
                            IndustryGroupColor = "#781acf",
                            IndustryGroupFullName = "فعاليتهاي پشتيباني و كمكي حمل و نقل؛ فعاليتهاي آژانسهاي مسافرتي(63)",
                            IndustryGroupTitle = "پشتيباني حمل و نقل؛آژانسهاي مسافرتي",
                            IndustryRGB_B = "207",
                            IndustryRGB_G = "26",
                            IndustryRGB_R = "120"
                        },
                        new
                        {
                            IndustryGroupId = 72,
                            IndustryGroupCode = "72",
                            IndustryGroupColor = "#cf1abc",
                            IndustryGroupFullName = "كامپيوتروفعاليتهاي مربوطه(72)",
                            IndustryGroupTitle = "كامپيوتر و فعاليتهاي مربوطه",
                            IndustryRGB_B = "188",
                            IndustryRGB_G = "26",
                            IndustryRGB_R = "207"
                        },
                        new
                        {
                            IndustryGroupId = 23,
                            IndustryGroupCode = "23",
                            IndustryGroupColor = "#1e34af",
                            IndustryGroupFullName = "كك وفراورده هاي حاصل ازنفت(23)",
                            IndustryGroupTitle = "كك و فراورده هاي نفتی",
                            IndustryRGB_B = "175",
                            IndustryRGB_G = "52",
                            IndustryRGB_R = "30"
                        },
                        new
                        {
                            IndustryGroupId = 30,
                            IndustryGroupCode = "30",
                            IndustryGroupColor = "#1eaf67",
                            IndustryGroupFullName = "ماشين آلات دفتري وحسابداري(30)",
                            IndustryGroupTitle = "ماشين آلات دفتري وحسابداري",
                            IndustryRGB_B = "103",
                            IndustryRGB_G = "175",
                            IndustryRGB_R = "30"
                        },
                        new
                        {
                            IndustryGroupId = 31,
                            IndustryGroupCode = "31",
                            IndustryGroupColor = "#2f83ff",
                            IndustryGroupFullName = "ماشين آلات ودستگاههاي برقي(31)",
                            IndustryGroupTitle = "ماشين آلات و لوازم برقی",
                            IndustryRGB_B = "255",
                            IndustryRGB_G = "131",
                            IndustryRGB_R = "47"
                        },
                        new
                        {
                            IndustryGroupId = 36,
                            IndustryGroupCode = "36",
                            IndustryGroupColor = "#942fff",
                            IndustryGroupFullName = "مبلمان سايرمصنوعات(36)",
                            IndustryGroupTitle = "مبلمان ساير مصنوعات",
                            IndustryRGB_B = "255",
                            IndustryRGB_G = "47",
                            IndustryRGB_R = "148"
                        },
                        new
                        {
                            IndustryGroupId = 16,
                            IndustryGroupCode = "16",
                            IndustryGroupColor = "#9d6c33",
                            IndustryGroupFullName = "محصولات ازتوتون وتنباكو(16)",
                            IndustryGroupTitle = "توتون وتنباكو",
                            IndustryRGB_B = "51",
                            IndustryRGB_G = "108",
                            IndustryRGB_R = "157"
                        },
                        new
                        {
                            IndustryGroupId = 25,
                            IndustryGroupCode = "25",
                            IndustryGroupColor = "#0a5687",
                            IndustryGroupFullName = "محصولات ازلاستيك وپلاستيك(25)",
                            IndustryGroupTitle = "لاستيك وپلاستيك",
                            IndustryRGB_B = "135",
                            IndustryRGB_G = "86",
                            IndustryRGB_R = "10"
                        },
                        new
                        {
                            IndustryGroupId = 15,
                            IndustryGroupCode = "15",
                            IndustryGroupColor = "#0c4645",
                            IndustryGroupFullName = "محصولات غذائي وآشاميدنيها(15)",
                            IndustryGroupTitle = "غذائي وآشاميدنيها",
                            IndustryRGB_B = "69",
                            IndustryRGB_G = "70",
                            IndustryRGB_R = "12"
                        },
                        new
                        {
                            IndustryGroupId = 28,
                            IndustryGroupCode = "28",
                            IndustryGroupColor = "#1e34af",
                            IndustryGroupFullName = "محصولات فلزي فابريكي(28)",
                            IndustryGroupTitle = "فلزي فابريكي",
                            IndustryRGB_B = "175",
                            IndustryRGB_G = "52",
                            IndustryRGB_R = "30"
                        },
                        new
                        {
                            IndustryGroupId = 34,
                            IndustryGroupCode = "34",
                            IndustryGroupColor = "#1eaf67",
                            IndustryGroupFullName = "وسايل نقليه موتوري(34)",
                            IndustryGroupTitle = "وسايل نقليه موتوري",
                            IndustryRGB_B = "103",
                            IndustryRGB_G = "175",
                            IndustryRGB_R = "30"
                        });
                });

            modelBuilder.Entity("MsmtApp.Models.Class_Province", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvinceId"), 1L, 1);

                    b.Property<string>("ProvinceAdminLevel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProvinceAreaId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Geometry>("ProvinceCoordinates")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProvinceId");

                    b.ToTable("DB_Province");
                });

            modelBuilder.Entity("MsmtApp.Models.Class_Users", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("userId");

                    b.ToTable("DB_Users");

                    b.HasData(
                        new
                        {
                            userId = 1,
                            Email = "test@gmail.com",
                            isAdmin = true,
                            name = "admin",
                            password = "123456",
                            username = "admin"
                        });
                });

            modelBuilder.Entity("MsmtApp.Models.Class_County", b =>
                {
                    b.HasOne("MsmtApp.Models.Class_Province", "Province")
                        .WithMany("Relation_County")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("MsmtApp.Models.Class_FourDigitActivityGroup", b =>
                {
                    b.HasOne("MsmtApp.Models.Class_IndustryGroup", "IndustryGroup")
                        .WithMany("Relation_FourDigitActivityGroup")
                        .HasForeignKey("IndustryGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IndustryGroup");
                });

            modelBuilder.Entity("MsmtApp.Models.Class_IndustrialUnit", b =>
                {
                    b.HasOne("MsmtApp.Models.Class_FourDigitActivityGroup", "FourDigitActivityGroup")
                        .WithMany("Relation_IndustrialUnit")
                        .HasForeignKey("FDAG_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FourDigitActivityGroup");
                });

            modelBuilder.Entity("MsmtApp.Models.Class_FourDigitActivityGroup", b =>
                {
                    b.Navigation("Relation_IndustrialUnit");
                });

            modelBuilder.Entity("MsmtApp.Models.Class_IndustryGroup", b =>
                {
                    b.Navigation("Relation_FourDigitActivityGroup");
                });

            modelBuilder.Entity("MsmtApp.Models.Class_Province", b =>
                {
                    b.Navigation("Relation_County");
                });
#pragma warning restore 612, 618
        }
    }
}
